version: '3'

services:

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8082:8080

  mysql:
    container_name: mysql
    image: mysql:8.0.26
    restart: always
    ports:
      - "3037:3036"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mentor4you_db
      MYSQL_USER: mentor4you
      MYSQL_PASSWORD: 1234

  mongo_db:
    container_name: mongodb
    image: "mongo:5.0"
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: mentor4you_db

  backend:
    container_name: backend_mentor4you
    image: backend
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "mysql"
      - "mongo_db"
